from django.urls import path

from . import views
from apps.gso_inventory.views import (
    InventoryListView,
    InventoryDetailView,
    InventoryCreateView,
    InventoryUpdateView,
    InventoryDeleteView,
    InventoryAdjustView,
    IssueMaterialToRequestView,
    SubmitMaterialRequestView,
    ApproveMaterialRequestView,
    RejectMaterialRequestView,
)
from apps.gso_requests.views import (
    RequestDetailView,
    StaffRequestListView,
    AssignPersonnelView,
    ToggleEmergencyView,
    StaffRequestRemindView,
    ApproveRequestView,
    NotApplicableRequestView,
    UpdateWorkStatusView,
    CompleteRequestView,
    ReturnForReworkView,
    AddRequestMessageView,
    PersonnelTaskListView,
    PersonnelTaskHistoryView,
)
from apps.gso_reports.views import (
    WARCreateView,
    WARUpdateView,
    WorkReportsLandingView,
    WorkReportsDashboardDataView,
    WorkReportsMigrationView,
    IPMTReportView,
    ipmt_generate_accomplishment_view,
    ipmt_autosave_draft_view,
    SuccessIndicatorManageView,
    SuccessIndicatorUpdateView,
    WARExportView,
    FeedbackReportsView,
    RequestReportView,
)

app_name = 'gso_accounts'

urlpatterns = [
    path('version/', views.app_version_view, name='app_version'),
    path('login/', views.GsoLoginView.as_view(), name='login'),
    path('logout/', views.GsoLogoutView.as_view(), name='logout'),
    path('staff/dashboard/', views.StaffDashboardView.as_view(), name='staff_dashboard'),
    path('staff/dashboard/pending-requests/', views.StaffDashboardPendingRequestsView.as_view(), name='staff_dashboard_pending_requests'),
    path('staff/request-management/', StaffRequestListView.as_view(), name='staff_request_management'),
    path('staff/request-management/<int:pk>/', RequestDetailView.as_view(), name='staff_request_detail'),
    path('staff/request-management/<int:pk>/assign/', AssignPersonnelView.as_view(), name='staff_request_assign'),
    path('staff/request-management/<int:pk>/toggle-emergency/', ToggleEmergencyView.as_view(), name='staff_request_toggle_emergency'),
    path('staff/request-management/<int:pk>/remind/', StaffRequestRemindView.as_view(), name='staff_request_remind'),
    path('staff/request-management/<int:pk>/approve/', ApproveRequestView.as_view(), name='staff_request_approve'),
    path('staff/request-management/<int:pk>/not-applicable/', NotApplicableRequestView.as_view(), name='staff_request_not_applicable'),
    path('staff/request-management/<int:pk>/status/', UpdateWorkStatusView.as_view(), name='staff_request_update_status'),
    path('staff/request-management/<int:pk>/complete/', CompleteRequestView.as_view(), name='staff_request_complete'),
    path('staff/request-management/<int:pk>/return-rework/', ReturnForReworkView.as_view(), name='staff_request_return_rework'),
    path('staff/request-management/<int:pk>/message/', AddRequestMessageView.as_view(), name='staff_request_message'),
    path('staff/request-management/<int:pk>/issue-material/', IssueMaterialToRequestView.as_view(), name='staff_request_issue_material'),
    path('staff/request-management/<int:pk>/request-material/', SubmitMaterialRequestView.as_view(), name='staff_request_material_submit'),
    path('staff/material-request/<int:mr_pk>/approve/', ApproveMaterialRequestView.as_view(), name='staff_material_request_approve'),
    path('staff/material-request/<int:mr_pk>/reject/', RejectMaterialRequestView.as_view(), name='staff_material_request_reject'),
    path('staff/request-management/<int:request_pk>/war/add/', WARCreateView.as_view(), name='staff_war_add'),
    path('staff/work-reports/war/<int:pk>/edit/', WARUpdateView.as_view(), name='staff_war_edit'),
    path('staff/request-history/', views.StaffRequestHistoryView.as_view(), name='staff_request_history'),
    path('staff/personnel-management/', views.StaffPersonnelManagementView.as_view(), name='staff_personnel_management'),
    path('staff/inventory/', InventoryListView.as_view(), name='staff_inventory'),
    path('staff/inventory/add/', InventoryCreateView.as_view(), name='staff_inventory_add'),
    path('staff/inventory/<int:pk>/', InventoryDetailView.as_view(), name='staff_inventory_detail'),
    path('staff/inventory/<int:pk>/edit/', InventoryUpdateView.as_view(), name='staff_inventory_edit'),
    path('staff/inventory/<int:pk>/delete/', InventoryDeleteView.as_view(), name='staff_inventory_delete'),
    path('staff/inventory/<int:pk>/adjust/', InventoryAdjustView.as_view(), name='staff_inventory_adjust'),
    path('staff/reports/', views.StaffReportsView.as_view(), name='staff_reports'),
    path('staff/task-management/', PersonnelTaskListView.as_view(), name='staff_task_management'),
    path('staff/task-history/', PersonnelTaskHistoryView.as_view(), name='staff_task_history'),
    path('staff/work-reports/', WorkReportsLandingView.as_view(), name='staff_work_reports'),
    path(
        'staff/work-reports/dashboard-data/',
        WorkReportsDashboardDataView.as_view(),
        name='staff_work_reports_dashboard_data',
    ),
    path('staff/work-reports/migrate-report/', WorkReportsMigrationView.as_view(), name='staff_work_reports_migrate_report'),
    path('staff/work-reports/ipmt/', IPMTReportView.as_view(), name='staff_work_reports_ipmt'),
    path('staff/work-reports/ipmt/generate-accomplishment/', ipmt_generate_accomplishment_view, name='staff_work_reports_ipmt_generate_accomplishment'),
    path('staff/work-reports/ipmt/autosave-draft/', ipmt_autosave_draft_view, name='staff_work_reports_ipmt_autosave_draft'),
    path('staff/work-reports/success-indicators/', SuccessIndicatorManageView.as_view(), name='staff_work_reports_success_indicators'),
    path('staff/work-reports/success-indicators/<int:pk>/edit/', SuccessIndicatorUpdateView.as_view(), name='staff_work_reports_success_indicator_edit'),
    path('staff/work-reports/war-export/', WARExportView.as_view(), name='staff_work_reports_war_export'),
    path('staff/work-reports/request-report/', RequestReportView.as_view(), name='staff_work_reports_request_report'),
    path('staff/work-reports/feedback/', FeedbackReportsView.as_view(), name='staff_work_reports_feedback'),
    path('staff/account-management/', views.StaffAccountManagementView.as_view(), name='staff_account_management'),
    path('staff/account-management/user/add/', views.DirectorUserCreateView.as_view(), name='staff_account_user_add'),
    path('staff/account-management/user/add/verify/', views.DirectorUserCreateVerifyView.as_view(), name='staff_account_user_add_verify'),
    path('staff/account-management/user/<int:pk>/edit/', views.DirectorUserEditView.as_view(), name='staff_account_user_edit'),
    path('staff/account-management/user/<int:pk>/api-keys/', views.UserApiKeysPanelView.as_view(), name='staff_user_api_keys'),
    path('staff/account-management/user/<int:pk>/status-action/', views.UserStatusActionView.as_view(), name='staff_account_user_status_action'),
    path('staff/account-management/user/<int:pk>/delete-permanent/', views.UserDeletePermanentView.as_view(), name='staff_account_user_delete_permanent'),
    path('staff/account-management/assign-oic/', views.AssignOICView.as_view(), name='staff_assign_oic'),
    path('staff/account-management/revoke-oic/', views.RevokeOICView.as_view(), name='staff_revoke_oic'),
    path('staff/activity-log/', views.StaffActivityLogView.as_view(), name='staff_activity_log'),
    path('staff/inventory-activity-log/', views.UnitHeadInventoryActivityLogView.as_view(), name='staff_inventory_activity_log'),
    path('staff/notifications/', views.StaffNotificationsView.as_view(), name='staff_notifications'),
    path('staff/profile/edit/', views.StaffProfileEditView.as_view(), name='staff_profile_edit'),
    path('requestor/dashboard/', views.RequestorDashboardView.as_view(), name='requestor_dashboard'),
    path('notifications/<int:pk>/go/', views.NotificationGoView.as_view(), name='notification_go'),
    path('notifications/mark-all-read/', views.MarkAllNotificationsReadView.as_view(), name='notification_mark_all_read'),
    path('requestor/notifications/', views.RequestorNotificationsView.as_view(), name='requestor_notifications'),
    path('requestor/profile/', views.RequestorProfileView.as_view(), name='requestor_profile'),
    path('requestor/profile/edit/', views.RequestorProfileEditView.as_view(), name='requestor_profile_edit'),
    path('password-change/', views.GsoPasswordChangeView.as_view(), name='password_change'),
    # Password reset
    path('password-reset/', views.GsoPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.GsoPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/verify/', views.GsoPasswordResetOTPVerifyView.as_view(), name='password_reset_verify'),
    path('password-reset/resend-otp/', views.GsoPasswordResetOTPResendView.as_view(), name='password_reset_resend_otp'),
    path('password-reset/new-password/', views.GsoPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', views.GsoPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('invite/set-password/<uidb64>/<token>/', views.AccountInviteSetPasswordView.as_view(), name='invite_set_password'),
]
