# Generated by Django 5.2.1 on 2026-02-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0001_add_request_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='gso_requests/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='request',
            name='custom_contact_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='request',
            name='custom_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='request',
            name='custom_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='labor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='materials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='others',
            field=models.BooleanField(default=False),
        ),
    ]
