# Generated by Django 5.2.1 on 2026-02-22 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0002_add_request_form_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(limit_choices_to={'role': 'PERSONNEL'}, on_delete=django.db.models.deletion.CASCADE, related_name='request_assignments', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='gso_requests.request')),
            ],
            options={
                'verbose_name': 'request assignment',
                'verbose_name_plural': 'request assignments',
                'ordering': ['assigned_at'],
                'unique_together': {('request', 'personnel')},
            },
        ),
    ]
