# Generated by Django 5.2.1 on 2026-02-22 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0003_add_request_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('DIRECTOR_APPROVED', 'Director Approved'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('DONE_WORKING', 'Done working'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=32),
        ),
        migrations.CreateModel(
            name='RequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gso_requests.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'request message',
                'verbose_name_plural': 'request messages',
                'ordering': ['created_at'],
            },
        ),
    ]
