# Generated by Django 5.2.1 on 2026-02-22 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0004_phase5_status_and_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 (low) to 5 (high)')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='gso_requests.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'request feedback',
                'verbose_name_plural': 'request feedback',
                'ordering': ['-created_at'],
                'unique_together': {('request', 'user')},
            },
        ),
    ]
