# Generated by Django 5.2.1 on 2026-02-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0005_add_request_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfeedback',
            name='cc1',
            field=models.CharField(blank=True, choices=[('', ''), ('know_saw', "I know what a CC is and I saw this office's CC"), ('know_no_saw', "I know what a CC is but I did not see this office's CC"), ('learned_here', "I learned of the CC only when I saw this office's CC"), ('no_know', 'I do not know what a CC is and I did not see one in this office')], max_length=32),
        ),
        migrations.AddField(
            model_name='requestfeedback',
            name='cc2',
            field=models.CharField(blank=True, choices=[('', ''), ('easy', 'Easy to see'), ('somewhat', 'Somewhat easy to see'), ('difficult', 'Difficult to see'), ('not_visible', 'Not visible at all')], max_length=32),
        ),
        migrations.AddField(
            model_name='requestfeedback',
            name='cc3',
            field=models.CharField(blank=True, choices=[('', ''), ('very_much', 'Helped very much'), ('somewhat', 'Somewhat helped'), ('no_help', 'Did not help')], max_length=32),
        ),
        migrations.AddField(
            model_name='requestfeedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='requestfeedback',
            name='sqd1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='requestfeedback',
            name='sqd2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='requestfeedback',
            name='sqd3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='requestfeedback',
            name='sqd4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='requestfeedback',
            name='sqd5',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='requestfeedback',
            name='sqd6',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='requestfeedback',
            name='sqd7',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='requestfeedback',
            name='sqd8',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='requestfeedback',
            name='sqd9',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='requestfeedback',
            name='suggestions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requestfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
