# Generated by Django 5.2.1 on 2026-02-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0006_csm_feedback_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_emergency',
            field=models.BooleanField(default=False, help_text='Unit Head marks as emergency (e.g. school president request). Shown at top for Director/GSO.'),
        ),
    ]
