# Generated by Django 5.2.1 on 2026-03-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0008_remove_priority_emergency_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requestor_cancel_reason',
            field=models.TextField(blank=True, help_text='Reason given by requestor when they cancelled (before work started).'),
        ),
        migrations.AddField(
            model_name='request',
            name='requestor_cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('DIRECTOR_APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('DONE_WORKING', 'Done working'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=32),
        ),
    ]
