# Generated by Django 5.2.1 on 2026-04-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0009_requestor_cancel_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('DIRECTOR_APPROVED', 'Approved'), ('INSPECTION', 'Inspection'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('DONE_WORKING', 'Done working'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=32),
        ),
    ]
