# Generated by Django 5.2.1 on 2026-04-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0010_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
