# Generated by Django 5.2.1 on 2026-04-29 07:45

import apps.gso_requests.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0012_request_work_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=apps.gso_requests.storage.GoogleDriveStorage(), upload_to='gso_requests/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='MotorpoolTripData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_office', models.CharField(blank=True, default='', max_length=255)),
                ('places_to_be_visited', models.TextField(blank=True, default='')),
                ('itinerary_of_travel', models.TextField(blank=True, default='', help_text='Newline-separated lines to drive ticket row count.')),
                ('trip_datetime', models.DateTimeField(blank=True, null=True)),
                ('number_of_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_of_passengers', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('contact_number', models.CharField(blank=True, default='', max_length=32)),
                ('driver_name', models.CharField(blank=True, default='', max_length=255)),
                ('vehicle_plate', models.CharField(blank=True, default='', max_length=64)),
                ('vehicle_stamp_or_contract_no', models.CharField(blank=True, default='', max_length=64)),
                ('vehicle_trans', models.CharField(blank=True, default='', max_length=64)),
                ('actual_legs_json', models.JSONField(blank=True, default=list)),
                ('fuel_beginning_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fuel_received_issued_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fuel_added_purchased_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fuel_total_available_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fuel_used_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fuel_ending_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('other_consumables_json', models.JSONField(blank=True, default=list)),
                ('other_consumables_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motorpool_trip', to='gso_requests.request')),
            ],
            options={
                'verbose_name': 'motorpool trip data',
                'verbose_name_plural': 'motorpool trip data',
            },
        ),
    ]
