# Generated by Django 5.2.1 on 2026-05-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gso_notifications', '0003_notification_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='gso_notific_user_id_a2b429_idx',
            old_name='gso_notific_user_id_3f08da_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='gso_notific_user_id_19cf7f_idx',
            old_name='gso_notific_user_id_760dfa_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='gso_notific_user_id_4f6dd0_idx',
            old_name='gso_notific_user_id_a6443f_idx',
        ),
    ]
