# Generated by Django 5.2.1 on 2026-02-22 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gso_requests', '0004_phase5_status_and_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAccomplishmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='Start of the work period covered by this report.')),
                ('period_end', models.DateField(help_text='End of the work period covered by this report.')),
                ('summary', models.CharField(blank=True, help_text='Short summary or title.', max_length=255)),
                ('accomplishments', models.TextField(blank=True, help_text='Description of work accomplished.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='war_created', to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(help_text='Personnel who did the work (must be assigned to this request).', limit_choices_to={'role': 'PERSONNEL'}, on_delete=django.db.models.deletion.CASCADE, related_name='work_accomplishment_reports', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_accomplishment_reports', to='gso_requests.request')),
            ],
            options={
                'verbose_name': 'work accomplishment report',
                'verbose_name_plural': 'work accomplishment reports',
                'ordering': ['-period_end', '-created_at'],
                'unique_together': {('request', 'personnel')},
            },
        ),
    ]
