# Generated by Django 5.2.1 on 2026-02-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_reports', '0001_war_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code, e.g. SI-01', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Order in lists/dropdowns')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'success indicator',
                'verbose_name_plural': 'success indicators',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='workaccomplishmentreport',
            name='success_indicators',
            field=models.ManyToManyField(blank=True, help_text='Success indicators this work aligns to (Phase 6.2).', related_name='work_accomplishment_reports', to='gso_reports.successindicator'),
        ),
    ]
