# Generated by Django 5.2.1 on 2026-04-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_reports', '0002_success_indicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='workaccomplishmentreport',
            name='labor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Labor cost for this work entry.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='workaccomplishmentreport',
            name='material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Material cost for this work entry.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='workaccomplishmentreport',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-computed total cost (material + labor).', max_digits=12, null=True),
        ),
    ]
