# Generated by Django 5.2.1 on 2026-02-22 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oic_for_director',
            field=models.ForeignKey(blank=True, help_text='Director who designated this user as Officer-in-Charge (OIC).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oic_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
