# Generated by Django 5.2.1 on 2026-02-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_accounts', '0003_phase9_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_code',
            field=models.CharField(blank=True, choices=[('man1', 'Man 1'), ('man2', 'Man 2'), ('man3', 'Man 3'), ('man4', 'Man 4'), ('man5', 'Man 5'), ('man6', 'Man 6'), ('man7', 'Man 7'), ('man8', 'Man 8'), ('man9', 'Man 9'), ('woman1', 'Woman 1'), ('woman2', 'Woman 2'), ('woman3', 'Woman 3'), ('woman4', 'Woman 4'), ('woman5', 'Woman 5'), ('woman6', 'Woman 6'), ('woman7', 'Woman 7'), ('woman8', 'Woman 8')], default='man1', help_text='Static avatar image key (man1–man9, woman1–woman8).', max_length=20),
        ),
    ]
